spring.application.name=route-guardian

spring.datasource.url=jdbc:postgresql://localhost:5432/route_guardian
spring.datasource.username=biker_admin
spring.datasource.password=ride_safe
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true